name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0-rc.1"

      - name: Test
        run: go test -v -race ./...
        env:
          GANDI_TOKEN: ${{ secrets.GANDI_TOKEN }}
